# Generated by Django 5.0 on 2025-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='portfolio-images')),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
            },
        ),
    ]
